name: FreedomHostingMod
main: com.tylerhyperHD.FreedomHostingMod.FreedomHostingMod
version: 1.0
description: A mod with a new eye for freedom.
authors: [tylerhyperHD]

commands:
   fhm:
      description: Main command for FHM
   purple:
      description: Grace the world with purple
   smite:
       description: Smite a player down.
   opall:
       description: Op every current online player.